export const pretty_print_mappings = {
  EXCLAMATION: "!",
  EXCL: "!",
  AT_SIGN: "@",
  AT: "@",
  HASH: "#",
  POUND: "#",
  DOLLAR: "$",
  DLLR: "$",
  PERCENT: "%",
  PRCNT: "%",
  CARET: "^",
  AMPERSAND: "&",
  AMPS: "&",
  ASTERISK: "*",
  ASTRK: "*",
  STAR: "*",
  LEFT_PARENTHESIS: "(",
  LPAR: "(",
  RIGHT_PARENTHESIS: ")",
  RPAR: ")",
  MINUS: "-",
  PLUS: "+",
  EQUAL: "=",
  LBKT: "[",
  RBKT: "]",
  LBRC: "{",
  RBRC: "}",
  PIPE: "|",
  KP_PLUS: "#+",
  TILDE: "~",
  COMMA: ",",
  PERIOD: ".",
  DOT: ".",
  BSLH: "\\",
  RET: "⮠ ",
  LGUI: "GUI",
  RGUI: "GUI",
  LALT: "ALT",
  RALT: "ALT",
  DQT: '"',
  CLCK: "CAPS",
  LEFT: "<-",
  RIGHT: "->",
  RGHT: "->",
  UP: "^",
  DOWN: "v",
  GRAVE: "`",
  LESS_THAN: "<",
  LT: "<",
  GREATER_THAN: ">",
  GT: ">",

  QMARK: "?",
  QUESTION: "?",

  SLASH: "/",
  FSLH: "/",

  MINS: "-",
  TILD: "~",
  COMM: ",",
  LPRN: "(",
  RPRN: ")",
  AMPR: "&",
  EXLM: "!",
  UNDS: "_",
  BSLS: "\\",
  SLSH: "/",
  GRV: "`",
  SCLN: ";",
  EQL: "=",
  QUOT: "'",

  PERC: "%",
  DLR: "$",
  COLN: ":",

  KP_SLASH: "#/",
  KP_ASTERISK: "#*",
  KP_MINUS: "#-",
  KP_ENTER: "#Enter",

  PSLS: "#/",
  PAST: "#*",
  PMNS: "#-",
  PPLS: "#+",
  PENT: "#⮠",

  NUBS: "\\",
};
